services:
  - type: web
    name: chatbot-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application --workers 1 --threads 2 --timeout 120 --max-requests 100 --max-requests-jitter 10"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: True
